### ISSUE TITLE
Not working in secure environnement (https://)

### ISSUE THREAD

**Issue by lucalbert** [ecoco/magento_profiler#4] opened 2016-10-20 09:16 UTC
Hello,

Congratulations for your module!

Unfortunately, it does not work properly when Magento works in https.

Indeed, in this mode, [Magento adds a new session entry](https://github.com/lalbert/magento-mirror/blob/master/app/code/core/Mage/Core/Model/Session/Abstract/Varien.php#L136).

However, this is only a **`string`** and **not a `array`**, creating a fatal error on Request panel because of the [`foreach` loop in the table.phtml template file](https://github.com/ecoco/magento_profiler/blob/master/app/design/frontend/base/default/template/ecocode_profiler/renderer/table.phtml#L16) (in this case, `$this->getItems()` returns a `string`).

**Comment by Fantus** [comment] 2016-10-20 09:35
Hi lucalbert,

thanks for the feedback, Unfortunately iam unable to reproduce it atm. https seems to work fine for me so it would be nice if you can give me some more details?

Which magento version are you using?

**Comment by lucalbert** [comment] 2016-10-20 09:47
Hi @Fantus,

I use Magento 1.9.2.4.

Magento run on full https environment (`unsecure_base_url` and `secure_base_url` is same and begin with https://).

**Comment by Fantus** [comment] 2016-10-20 10:00
Hi @lucalbert,

thx i could reproduce it an pushed a fix. thx for the pull request, but the issue was not related to the table renderer itself it was more an issue with the panel of the request it self:
https://github.com/ecoco/magento_profiler/commit/53cfec3c932c69cadae5cc9e5dd24aa56477be09

**Closed as completed by Fantus** 2016-10-20 10:00 UTC

**Comment by lucalbert** [comment] 2016-10-20 10:20
It's work fine !

Thx.
